fumieval/witherable

src/Data/Witherable.hs, witherable.cabal
Currently, `witherable` defines orphan `Foldable`/`Traversable` instances for `Const` and `Either`. However, there are a number of other packages that also define these instances, including [`functor-combo`](https://github.com/conal/functor-combo/blob/885752a0b58a2e9e606401da9ed8a4f0fe823680/src/FunctorCombo/Functor.hs#L115-118), [`semigroupoids`](https://github.com/ekmett/semigroupoids/blob/99ce7a18876da749c49e8ee969ff03a340fb76af/src/Data/Traversable/Instances.hs#L36-56), and [`lens`](https://github.com/ekmett/lens/blob/7af45fb03374ef23a3658c17e692ea475f6bf585/src/Control/Lens/Internal/Instances.hs#L44-70), which means that if anyone were to use any combination of these libraries together on GHC 7.6 or earlier, it could lead to instance conflicts.
To help mitigate this possibility, this …
=> Use base-orphans to import Foldable/Traversable orphan instances

src/Data/Witherable.hs, witherable.cabal
I need it, please export.
or add the following combinator.
```haskell
darken :: LensLike (MaybeT f) s t a b -> LensLike f s (Maybe t) a (Maybe b)
darken l f s = runMaybeT $ l (MaybeT . f) s
```
=> Export 'witherM', 'blightM'

src/Data/Witherable.hs
`ordNub`'s documentation claims to be "exponentially quicker" than `nub` from Prelude, but unless I misunderstand, `ordNub` is O(n*log(n)) and `nub` is O(n^2), which is less than a factor of `n` improvement, which is not "exponentially" faster.
=> Possibly correct documentation error

src/Data/Witherable.hs
The conservation law I had added to `Witherable` was ill-typed. Also, I added a similar law to `Filterable`. Currently, the laws for `Filterable` are:
mapMaybe Just ≡ id
mapMaybe f . mapMaybe g ≡ mapMaybe (f <=< g)
We are currently missing anything that relates the to the superclass `Functor` constraint. It's possible that the law I've added is actually implied by the identity law, but I cannot tell.
=> fix conservation law for Witherable. add conservation law to Filterable

witherable.cabal
We depend on Data.Map.Lazy, meaning that we need a containers version
at or above 0.5. This fixes the build on GHC 7.4 and below.
=> Put a lower bound on containers

src/Data/Witherable.hs
Add instances for `Data.Functor.Sum`, `Data.Functor.Product`,
and `Control.Monad.Trans.Identity`.
=> Add more algebraic instances

witherable.cabal
`Data.Functor.Sum` appears to have some weird history I don't
understand (it kind of looks like it might have moved twice
or accidentally disappeared at one point). Let's see if adding
a `transformers-compat` dependency will fix that.
=> Add transformers-compat dependency

src/Data/Witherable.hs, witherable.cabal
This PR adds infix operators inspired by `(<$>)` and `(<&>)`. Adding `?` to the operator names seemed like a natural choice.
I've used the same fixites as the operators from `Data.Functor`, but can change this if required.
I bumped the package version in the hopes of a speedy hackage release but can undo that if required also.
=> Add (<$?>) and (<&?>). Fixities match (<$>) and (<&>) respectively

CHANGELOG.md
I forgot a changelog entry for the new infix operators. This PR corrects that.
=> Add changelog entries for infix operators

CHANGELOG.md, src/Data/Witherable.hs, witherable.cabal
This incurs a direct dependency on `lens`, but there is already a
transitive dependency going through `monoidal-map`.
I didn't add `IndexedFilter` and allies, mostly because it was
complicated and isn't necessary to get something useful here - just
being able to generalise `traverseMapWithKey` is quite handy already.
Closes #40.
=> Add indexed operations.

src/Data/Witherable.hs, witherable.cabal
Make the Wcompat flag only active on GHC versions where it exists
=> Fix building on GHC 7.10

src/Data/Witherable.hs
`Option` will eventually be deprecated but it will be around for a while, even after that...
=> Add instances for Option

src/Data/Witherable.hs
I think there should be instances for the `ZipList` newtype from `Control.Applicative`.
=> Ziplist instances

src/Data/Witherable.hs
* Add explicit implementations of `witherM` and `filterA` for many
types, mostly leaning on underlying implementations of those types.
* Use `mapM` rather than `traverse` when implementing `witherM`
generally, is any special monadic optimizations are likely to be
expected.
* Make `V1` instances a bit more defined, to match its `Traversable`
instance.
=> Various cleanups

witherable-class/Data/Witherable/Class.hs
Note that the `t` in the naturality law must be an applicative
transformation.
Fixes #59
=> Add condition to naturality law

witherable-class/Data/Witherable/Class.hs
`(&&)` evaluates its left hand side first, short-circuiting and not evaluating its right hand side when the left side is `False`. In `filter f . filter g`, `g` is evaluated first. This might come up in practice with a situation like `filter (\(Just x) -> p x) . filter isJust`, where testing the left condition first would produce bottom.
=> Fix short-circuiting behavior of the `filter` law.

witherable-class/Data/Witherable/Class.hs
These instances provide Filterable and Witherable for records:
```
data Example a = Example {
someNumber :: Int,
things :: [a]
} deriving Generic1
instance Filterable Example where
catMaybes = to1 . catMaybes . from1
mapMaybe f = to1 . mapMaybe f . from1
filter p = to1 . filter p . from1
instance Witherable Example where
wither f = fmap to1 . wither f . from1
filterA p = fmap to1 . filterA p . from1
```
Do they have any adverse effects or break any laws?
=> Instances for Generics.K1

witherable/CHANGELOG.md, witherable/src/Witherable.hs, witherable/tests/tests.hs
In my cursory benchmarks I don't notice considerable performance
changes. For lists this is a win.
=> Resolve #74. Nub functions are now productive

witherable/src/Data/Witherable.hs, witherable/src/Witherable.hs
Checked with
```cabal
packages:
./witherable/
./witherable-class/
allow-newer:
indexed-traversable-instances:base,
indexed-traversable:base,
quickcheck-instances:base,
splitmix:base,
time-compat:base,
these:base,
assoc:base,
integer-logarithms:base,
integer-logarithms:ghc-bignum,
integer-logarithms:ghc-prim,
data-fix:base
```
=> Fixes for GHC 9.2

witherable/src/Witherable.hs
Provides a generic `partitionWith`,  `witherable` seems to be the logical place for such a thing, as it can be implemented in terms of the existing `Filterable` class.
I added it to the `Filterable` class because more efficient versions may be available.
Existing names I've found for this operation: [Vector's `partitionWith`](https://hackage.haskell.org/package/vector-0.13.0.0/docs/Data-Vector.html#v:partitionWith), [base's `partitionEithers`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Either.html#v:partitionEithers), [containers' `mapEither`](https://hackage.haskell.org/package/containers-0.6.7/docs/Data-Map-Internal.html#v:mapEither).
I chose `partitionWith`, and `partitionEithers`, but I don't have a strong opinion on the name (although I'd prefer not to add a new name …
=> feat: Add partitionWith, partitionWithA, partitionEithers
